# Generated by Django 2.2.4 on 2019-08-20 02:23

from django.db import migrations, models
import factory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='CREATE', max_length=256)),
                ('name', models.CharField(default='UNKNOWN', max_length=256)),
                ('task_id', models.CharField(default='ERROR', max_length=64)),
                ('session', models.CharField(default='NONE', max_length=256)),
                ('start', models.FloatField(default=0)),
                ('runtime', models.FloatField(default=0)),
                ('errors', models.TextField(default='')),
                ('results', factory.models.CompressedTextField(default='[]')),
            ],
            options={
                'db_table': 'factory.tasks',
            },
        ),
    ]
